// module.exports={
//     devServer:{        
//         proxy:{
//           '/dddd':{
//          target:'http://localhost:8000',
//             changeOrigin:true,
//             pathRewrite:{
//               '^/dddd':''
//             }
//           }
//         }
//     }
// }